hsbctl: better operator setup code

diff --git a/hsbctl b/hsbctl
--- a/hsbctl
+++ b/hsbctl
@@ -397,6 +397,38 @@ function reportSanboxInfo {
 	fi
 }
 
+function setupHelmAndOperator {
+  # sleep is needed or the cert manager will refuse connection and the install will fail
+  # if this is run too soon after an init it will fail because things are too busy
+  if which helm > /dev/null 2>&1; then
+    kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.8.0/cert-manager.yaml --wait
+    echo "[INFO]Sleeping for 30 seconds to allow the cert-manager to start, be patient"
+    sleep 30
+    kubectl create namespace tyk-operator-system
+    #kubectl create secret -n tyk-operator-system generic tyk-operator-conf --from-literal "TYK_TLS_INSECURE_SKIP_VERIFY=true"
+    kubectl create secret -n tyk-operator-system generic tyk-operator-conf --from-literal "FRED=true"
+    helm repo add tyk-helm https://helm.tyk.io/public/helm/charts/
+    helm repo update
+    echo "[INFO]Attempting to deploy operator using helm. This may take a while"
+    if ! helm install tyk-operator tyk-helm/tyk-operator -n tyk-operator-system --atomic ; then
+      echo "[WARN]Operator install failed. Retrying, but only once"
+      kubectl delete ns tyk-operator-system --wait
+      kubectl create namespace tyk-operator-system
+      #kubectl create secret -n tyk-operator-system generic tyk-operator-conf --from-literal "TYK_TLS_INSECURE_SKIP_VERIFY=true"
+      kubectl create secret -n tyk-operator-system generic tyk-operator-conf --from-literal "FRED=true"
+      sleep 10
+      echo "[INFO]Reattempting to deploy operator using helm. This may take a while"
+      if ! helm install tyk-operator tyk-helm/tyk-operator -n tyk-operator-system; then
+        echo "[FATAL]Unable to deploy operator after two attempts, giving up"
+        exit 1
+      fi
+    fi
+  else
+    echo "[FATAL]Helm not installed. Please install helm and retry"
+    exit 1
+  fi
+}
+
 # process commands
 if [[ $# -gt 0 ]]; then
 	case $1 in
@@ -535,13 +567,7 @@ if [[ $# -gt 0 ]]; then
 			;;
 		setup)
 			# needs to install the helm charts, cert manager and setup the tyk-operator-system namespace
-			# install cert manager
-			kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.8.0/cert-manager.yaml
-			helm repo add tyk-helm https://helm.tyk.io/public/helm/charts/
-			helm repo update
-			kubectl create namespace tyk-operator-system
-			kubectl create secret -n tyk-operator-system generic tyk-operator-conf --from-literal "TYK_TLS_INSECURE_SKIP_VERIFY=true"
-			helm install tyk-operator tyk-helm/tyk-operator -n tyk-operator-system
+			setupHelmAndOperator
 			;;
 		shell)
 			shift
