hsbctl: implemented local operator context

diff --git a/hsbctl b/hsbctl
--- a/hsbctl
+++ b/hsbctl
@@ -70,6 +70,9 @@ SCRIPTNAME=$(basename $SCRIPTNAME)
 VERSIONFILE="$SCRIPTDIR/tyk-versions.list"
 YAMLDIR="$SCRIPTDIR/YAML"
 APIDIR="$SCRIPTDIR/APIs"
+PUBLISH_APIS=true
+OPERATOR_CONTEXT_NAME=local-operator-context
+OPERATOR_MASK_URL=http://httpbin.org/anything/200
 
 NAMESPACE_SELECTOR_LABEL="creator=hsbctl"
 ISTIO_INJECTION_LABEL='istio-injection=enabled'
@@ -215,6 +218,7 @@ function help {
   echo "         Incompatible with -R"
   echo "      -N Use the given namespace name rather than the next available sandbox"
   echo "         Useful when there's a need to import apis and policy YAML with set namespace"
+  echo "      -n Don't publish sample APIs"
   echo "      -O MDCB rpc_key (orgid)"
   echo "         Used by data plane only and only when the control plane isn't a sandbox in the cluster"
   echo "         Incompatible with -R"
@@ -273,6 +277,101 @@ function createApiDefintion {
   echo '}'
 }
 
+# Create an operator context in the sandbox
+function deployOperatorContext {
+  typeset adminKey
+  typeset orgid
+  typeset OperatorContextYAML
+  OperatorContextYAML=$(mktemp /tmp/operatorContext.yaml.XXXX)
+  if [[ $HSBX_CHART == 'tyk-stack' || $HSBX_CHART == 'tyk-control-plane' ]]; then
+    # Dashboard (pro) install
+    typeset dashURL
+    adminkey=$(getAdminUserKey)
+    dashURL="http://$IP:$(getDashboardPort)/"
+    orgid=$(getOrgID)
+    echo "Deploying operator context into new Pro sandbox"
+    echo "apiVersion: tyk.tyk.io/v1alpha1" > $OperatorContextYAML
+    echo "kind: OperatorContext" >> $OperatorContextYAML
+    echo "metadata:" >> $OperatorContextYAML
+    echo "  name: $OPERATOR_CONTEXT_NAME" >> $OperatorContextYAML
+    echo "spec:" >> $OperatorContextYAML
+    echo "  env:" >> $OperatorContextYAML
+    echo "    mode: pro" >> $OperatorContextYAML
+    echo "    auth: $adminkey" >> $OperatorContextYAML
+    echo "    org: $orgid" >> $OperatorContextYAML
+    echo "    url: $dashURL" >> $OperatorContextYAML
+    echo "    insecureSkipVerify: true" >> $OperatorContextYAML
+    echo "[INFO]kubectl apply -f $OperatorContextYAML -n $NAMESPACE"
+    kubectl apply -f $OperatorContextYAML -n $NAMESPACE
+    rm -f $OperatorContextYAML
+  else
+    # stand alone (CE) deployment
+    echo "[FATAL]Deploy an operator context into type $HSBX_CHART"
+    rm -f $OperatorContextYAML
+    exit 1
+  fi
+}
+
+function CrdExists {
+  typeset namespace
+  typeset CRD
+  typeset CrdCount
+  namespace=$1
+  CRD=$2
+  CrdCount=0
+  if kubectl get crd -n $namespace --no-headers=true 2>&- | grep -iq "$CRD"; then
+    if [[ $(kubectl get $CRD -n $namespace --no-headers=true 2>&- | wc -l) -gt 0 ]]
+    then
+      return 0
+    fi
+  fi
+  return 1
+}
+
+function MaskOperatorContext {
+  typeset namespace
+  namespace=$1
+  if CrdExists $namespace operatorcontexts.tyk.tyk.io; then
+    kubectl get operatorcontext $OPERATOR_CONTEXT_NAME -n $namespace -o yaml | yq '.spec.env.url = "'$OPERATOR_MASK_URL'"' | kubectl apply -n $namespace -f -
+  fi
+}
+
+function RemoveTykCRDs {
+  typeset namespace
+  typeset CRD
+  namespace=$1
+  for CRD in portalapicatalogues apidescription securitypolicies subgraphs supergraphs apidefinitions tykoasapidefinitions tykstreamsapidefinitions portalconfigs; do
+    if CrdExists $namespace $CRD; then
+      echo "[INFO]Removing all $CRD from $namespace"
+      kubectl delete $CRD --all -n $namespace
+    fi
+  done
+}
+
+function OperatorContextExists {
+  if CrdExists $1 operatorcontexts.tyk.tyk.io
+  then
+    return 0
+  fi
+  return 1
+}
+
+# deploy APIs from YAML using operator context
+function deployCRDAPIs {
+  typeset APIsourceYaml
+  typeset tmpAPIyaml
+  tmpAPIyaml=$(mktemp /tmp/API.yaml.XXXX)
+  for APIsourceYaml in $*; do
+    if [[ -f $APIsourceYaml ]]; then
+      cp $APIsourceYaml $tmpAPIyaml
+      yq ".spec.contextRef.namespace = \"$NAMESPACE\"" -i $tmpAPIyaml
+      echo "[INFO]kubectl apply -f $tmpAPIyaml -n $NAMESPACE"
+      kubectl apply -f $tmpAPIyaml -n $NAMESPACE
+    fi
+  done
+  rm -f $tmpAPIyaml
+}
+
 # inject an API definition into a running sandbox
 function publishAPIs {
   typeset APIfile
@@ -328,28 +427,8 @@ function publishAPIs {
       echo "[WARN]Cannot get Adminkey so cannot publishAPIs"
     fi
   else
-    # stand alone (ce)
-    typeset gatewayPort
-    typeset APIs
-    typeset API
-    gatewayPort=$(getStandaloneGatewayPort)
-    APIs=""
-    API=""
-    # load the APIs
-    for APIfile in "$@"; do
-      echo "[INFO]Publishing API $APIfile"
-      curl -sH "x-tyk-authorization: $HSBX_GATE_SECRET" -d @$APIfile http://$IP:$gatewayPort/tyk/apis
-      echo "[INFO]Hot reloading the gateway"
-      curl -sH "x-tyk-authorization: $HSBX_GATE_SECRET" http://$IP:$gatewayPort/tyk/reload/group
-    done
-    # report on APIs reloaded
-    sleep 10
-    curl -sH "x-tyk-authorization: $HSBX_GATE_SECRET" http://$IP:$gatewayPort/tyk/apis | jq -r '.[].name' | while read API; do
-      APIs="'$API' $APIs"
-    done
-    if [[ -n $APIs ]]; then
-      echo "[INFO]Apis published: $APIs"
-    fi
+    echo "[FATAL]Cannot publish APIs with chart type $HSBX_CHART"
+    exit 1
   fi
 }
 
@@ -1100,6 +1179,15 @@ function getGatewayProtocol {
   fi
 }
 
+function getControlPlaneDashboardPort {
+  typeset namespace
+  namespace=$NAMESPACE
+  if [[ $# > 0 ]]; then
+    namespace="$1"
+  fi
+  kubectl get svc -n $NAMESPACE dashboard-svc-$HELM_TYKCONTROLPLANE_RELEASE_NAME-tyk-dashboard --no-headers=true | awk -F '[:/ ]+' '{print $6}'
+}
+
 function getDashboardPort {
   kubectl get svc -n $NAMESPACE dashboard-svc-$HELM_RELEASE_NAME-tyk-dashboard --no-headers=true | awk -F '[:/ ]+' '{print $6}'
 }
@@ -1614,7 +1702,7 @@ if [[ $# -gt 0 ]]; then
   case $1 in
     create)
       shift
-      while getopts :C:D:d:E:g:H:hK:M:N:O:PpR:r:Sst:V:v: arg; do
+      while getopts :C:D:d:E:g:H:hK:M:nN:oO:PpR:r:Sst:V:v: arg; do
         case $arg in
           C)
             # this is the chart to deploy. Defaults to tyk-stack
@@ -1663,9 +1751,22 @@ if [[ $# -gt 0 ]]; then
             # specify a particular namespace
             NAMESPACE=$OPTARG
             ;;
+          n)
+            # Don't publish sample APIs
+            PUBLISH_APIS=false
+            ;;
           O)
             # MDCB orgid/rpc_key (used when not connecting to a control plane created by this script)
             HSBX_REMOTE_CONTROL_PLANE_RPC_KEY=$OPTARG
+            ;;
+          o)
+            # deploy an operator context into the new namespace
+            if namespaceExists tyk-operator-system; then
+              INSTALL_OPR_CONTEXT=true
+            else
+              echo "[FATAL]Tyk operator is not installed. Install with '$SCRIPTNAME setup operator'"
+              exit 1
+            fi
             ;;
           P)
             # deploy devportal so must deploy PG as well then
@@ -1740,6 +1841,11 @@ if [[ $# -gt 0 ]]; then
           echo "[FATAL]All of -K, -M, -O must be set if any are"
           exit 1
         fi
+      fi
+      if [[ $INSTALL_OPR_CONTEXT == 'true' && $HSBX_CHART == 'tyk-data-plane' ]]; then
+        # For simplicity's sake lets not allow this.
+        echo "[FATAL]This script cannot deploy a local operator context into a dataplane. Do it manually if needed"
+        exit 1
       fi
       if [[ -z $NAMESPACE ]]; then
         NAMESPACE=hsandbox-$(nextFreeNamespace)
@@ -1839,7 +1945,16 @@ if [[ $# -gt 0 ]]; then
         runHelm
         if [[ $HSBX_CHART == 'tyk-stack' || $HSBX_CHART == 'tyk-control-plane' ]]; then
           saveOrgAndAdminKey
-          publishAPIs $APIDIR/*.yaml
+          if [[ $INSTALL_OPR_CONTEXT == 'true' ]]; then
+            deployOperatorContext
+            if [[ $PUBLISH_APIS == 'true' ]]; then
+              deployCRDAPIs $APIDIR/CRDs/*.yaml
+            fi
+          else
+            if [[ $PUBLISH_APIS == 'true' ]]; then
+              publishAPIs $APIDIR/*.yaml
+            fi
+          fi
         fi
         echo "[INFO]$NAMESPACE"
         showTykVersions
@@ -2102,6 +2217,14 @@ if [[ $# -gt 0 ]]; then
       for NAMESPACE in $(getNamespaceNames $*); do
         if namespaceExists $NAMESPACE; then
           echo "[INFO]Deleting Namespace $NAMESPACE"
+          if OperatorContextExists $NAMESPACE ]]; then
+            echo "[INFO]Deleting OperatorContext from $NAMESPACE"
+            MaskOperatorContext $NAMESPACE
+            RemoveTykCRDs $NAMESPACE
+            echo "[INFO]kubectl delete OperatorContext --all -n $NAMESPACE"
+            kubectl delete OperatorContext --all -n $NAMESPACE
+            echo "[INFO]kubectl delete namespace $NAMESPACE --wait"
+          fi
           kubectl delete namespace $NAMESPACE --wait
         fi
       done
